version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /packaging/docker
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /packaging/release
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /packaging/oci
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
